[package]
name = "durable-testkit"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
async-trait.workspace = true
durable-core.workspace = true
durable-journal.workspace = true
rand.workspace = true
thiserror.workspace = true
tokio.workspace = true
